name: Cli template update
 
on: [repository_dispatch]
 
jobs:
  update-parent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Git operation to update the template files
        run: |
          git config --global user.email "s.foucheur@gmail.com"
          git config --global user.name "Sfoucheur"
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/ngx-template/kli-cli.git
          cd kli-cli
          git checkout -b tempbranch
          git rm -r src/templates/angular-node
          git commit -m "delete angular-node"
          git subtree add --prefix src/templates/angular-node https://${{ secrets.ACCESS_TOKEN }}@github.com/ngx-template/ngx-template.git main --squash -m "update angular-node"
          npm install --silent
          node src/utils/convertToTemplate.js
          git add src/templates/angular-node
          git commit -m "convert to template"
          git checkout main
          git merge --squash --strategy-option theirs tempbranch
          git commit -m "update template"
          git push
